version: '3.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - prometheus
      - grafana
      - alertmanager
    links:
      - prometheus
    volumes:
      # 8081 -> http://prometheus:9090
      - ./etc/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      #- ./etc/nginx/cert/star_xx_com.pem:/etc/nginx/cert/star_xx_com.pem
      #- ./etc/nginx/cert/star_xx_com.key:/etc/nginx/cert/star_xx_com.key
      #- ./etc/nginx/cert/star_xx_com.crt:/etc/nginx/cert/star_xx_com.crt
    ports:
      - 8081:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    extra_hosts:
      - lab.enode.ro:192.168.1.103
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=96h'
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./etc/prometheus/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml:ro
    depends_on:
      - cadvisor

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./etc/alertmanager/:/alertmanager
      - ./var/alertmanager/data:/data
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:7.3.6-ubuntu
    container_name: grafana
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./var/grafana/data:/var/lib/grafana
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-prometheus
#    command:
#      - 'sysctl vm.overcommit_memory=1'
    ports:
      - 6379:6379
