groups:
  - name: custom_rules
    rules:
      - record: node_memory_MemFree_percent
        expr: 100 - (100 * node_memory_MemFree / node_memory_MemTotal)
      - record: node_filesystem_free_root_percent
        expr: 100 * node_filesystem_free{mountpoint="/"} / node_filesystem_size{mountpoint="/"}
      - record: node_filesystem_free_home_percent
        expr: 100 * node_filesystem_free{mountpoint="/home"} / node_filesystem_size{mountpoint="/home"}

  - name: alert_rules
    rules:

      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: DiskSpaceFreeRoot10Percent
        expr: node_filesystem_free_root_percent <= 10
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has 10% or less Root Free disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% or less free."

      - alert: DiskSpaceFreeRoot90Percent
        expr: node_filesystem_free_root_percent <= 90
        labels:
          severity: info
        annotations:
          summary: "Instance {{ $labels.instance }} has 90% or less Root Free disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% or less free."

      - alert: DiskSpaceFreeHome5Percent
        expr: node_filesystem_free_home_percent <= 5
        labels:
          severity: warning
        annotations:
          summary: "Instance {{ $labels.instance }} has 10% or less Home Free disk space"
          description: "{{ $labels.instance }} has only {{ $value }}% or less free."
